### ISSUE TITLE
intermittent access to Zenodo artifact https://zenodo.org/record/1480288/files/BM000561307.tif with hash://md5/54912d475b8653c8949100abb046bfd2

### ISSUE THREAD

**Issue by jhpoelen** [bio-guoda/preston-dillen-2018#1]
On running attempting to track TIFF files referenced in the Dillen 2018 summary file, I was unable to retrieve tif image:

https://zenodo.org/record/1480288/files/BM000561307.tif
with hash://md5/54912d475b8653c8949100abb046bfd2 (as reported by Zenodo see attached image)

related to 

https://zenodo.org/record/1480288

and 

Natural History Museum London. (2018). Herbarium specimen image of Polysiphonia strictissima Hook.f. & Harv., part of the collection of Natural History Museum London. Zenodo. https://doi.org/10.5281/zenodo.1480288

The Zenodo server is responding HTTP 404 not found. 

@matdillen @PietrH @slint - any idea why https://zenodo.org/record/1480288/files/BM000561307.tif is producing a 404 ? 

```
$  curl --verbose "https://zenodo.org/record/1480288/files/BM000561307.tif" > bla.tif
* TCP_NODELAY set
* Connected to zenodo.org (137.138.76.77) port 443 (#0)
> GET /record/1480288/files/BM000561307.tif HTTP/1.1
> Host: zenodo.org
> User-Agent: curl/7.68.0
> Accept: */*
> 
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0{ [5 bytes data]
* Mark bundle as not supporting multiuse
< HTTP/1.1 404 Not Found
< Server: nginx
< Date: Thu, 24 Mar 2022 19:49:15 GMT
< Content-Type: image/tiff
< Content-Length: 3846
< Content-Disposition: attachment; filename=BM000561307.tif
< Accept-Ranges: none
< Set-Cookie: session=1b141203c9449e67_623ccb3b.YGESHcSnNguhc6PzX36RHW54T6Y; Expires=Sun, 24-Apr-2022 19:49:15 GMT; Secure; HttpOnly; Path=/
< 
{ [3846 bytes data]
100  3846  100  3846    0     0   2574      0  0:00:01  0:00:01 --:--:--  2572
* Connection #0 to host zenodo.org left intact
```

![Screenshot from 2022-03-24 14-55-20](https://user-images.githubusercontent.com/1084872/159999457-72984f9c-7bbe-4421-8ba0-7c7e791cebb2.png)

**Comment by matdillen** [comment]
I have no idea. I also get 404 responses, but some tries get me 200 and the download redirect in browser as well. I've even seen 404 response, yet a delayed download job still getting launched in Chrome.

Is this the only record showing this behavior?

**Comment by jhpoelen** [comment]
@matdillen as far as I can tell, this is the only artifact from the json and tiff links referenced in your summary file. 

Weird right?

**Comment by jhpoelen** [comment]
@matdillen do you still have the original associated tiff file somewhere ?

**Comment by slint** [comment]
Thanks for finding and reporting @jhpoelen. I'm going through our logs to see why the response is "flaky". I tried multiple times as well to access the file and got about ~50% of the time 404s. It could be that some of our file storage replicas are acting up, so because of the round-robin load-balancing, we get this inconsistency.

**Comment by matdillen** [comment]
> @matdillen do you still have the original associated tiff file somewhere ?

I just retrieved it and it has the same hash as Zenodo reports and as the downloaded file. So I don't think it's a problem with the record itself.

**Comment by jhpoelen** [comment]
@slint @matdillen thanks for having a look at this, I'll try again today and patch the image corpus with the associated artifact.

I am seeing similar intermittent failures, 404s and timeouts. 

at ```2022-03-25T13:38:24.036Z``` Preston reported the following on ```https://zenodo.org/record/1480288/files/BM000561307.tif```

```
<https://preston.guoda.bio> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://www.w3.org/ns/prov#SoftwareAgent> <urn:uuid:4cdce8bc-4ca5-415a-b48e-36085c0240bc> .
<https://preston.guoda.bio> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://www.w3.org/ns/prov#Agent> <urn:uuid:4cdce8bc-4ca5-415a-b48e-36085c0240bc> .
<https://preston.guoda.bio> <http://purl.org/dc/terms/description> "Preston is a software program that finds, archives and provides access to biodiversity datasets."@en <urn:uuid:4cdce8bc-4ca5-415a-b48e-36085c0240bc> .
<urn:uuid:4cdce8bc-4ca5-415a-b48e-36085c0240bc> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://www.w3.org/ns/prov#Activity> <urn:uuid:4cdce8bc-4ca5-415a-b48e-36085c0240bc> .
<urn:uuid:4cdce8bc-4ca5-415a-b48e-36085c0240bc> <http://purl.org/dc/terms/description> "A crawl event that discovers biodiversity archives."@en <urn:uuid:4cdce8bc-4ca5-415a-b48e-36085c0240bc> .
<urn:uuid:4cdce8bc-4ca5-415a-b48e-36085c0240bc> <http://www.w3.org/ns/prov#startedAtTime> "2022-03-25T13:35:46.807Z"^^<http://www.w3.org/2001/XMLSchema#dateTime> <urn:uuid:4cdce8bc-4ca5-415a-b48e-36085c0240bc> .
<urn:uuid:4cdce8bc-4ca5-415a-b48e-36085c0240bc> <http://www.w3.org/ns/prov#wasStartedBy> <https://preston.guoda.bio> <urn:uuid:4cdce8bc-4ca5-415a-b48e-36085c0240bc> .
<https://doi.org/10.5281/zenodo.1410543> <http://www.w3.org/ns/prov#usedBy> <urn:uuid:4cdce8bc-4ca5-415a-b48e-36085c0240bc> <urn:uuid:4cdce8bc-4ca5-415a-b48e-36085c0240bc> .
<https://doi.org/10.5281/zenodo.1410543> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://purl.org/dc/dcmitype/Software> <urn:uuid:4cdce8bc-4ca5-415a-b48e-36085c0240bc> .
<https://doi.org/10.5281/zenodo.1410543> <http://purl.org/dc/terms/bibliographicCitation> "Jorrit Poelen, Icaro Alzuru, & Michael Elliott. 2021. Preston: a biodiversity dataset tracker (Version 0.0.1-SNAPSHOT) [Software]. Zenodo. http://doi.org/10.5281/zenodo.1410543"@en <urn:uuid:4cdce8bc-4ca5-415a-b48e-36085c0240bc> .
<urn:uuid:0659a54f-b713-4f86-a917-5be166a14110> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://www.w3.org/ns/prov#Entity> <urn:uuid:4cdce8bc-4ca5-415a-b48e-36085c0240bc> .
<urn:uuid:0659a54f-b713-4f86-a917-5be166a14110> <http://purl.org/dc/terms/description> "A biodiversity dataset graph archive."@en <urn:uuid:4cdce8bc-4ca5-415a-b48e-36085c0240bc> .
<hash://md5/721e8329e1cdffa06398bc5214a14d3e> <http://www.w3.org/ns/prov#usedBy> <urn:uuid:4cdce8bc-4ca5-415a-b48e-36085c0240bc> <urn:uuid:4cdce8bc-4ca5-415a-b48e-36085c0240bc> .
[main] WARN bio.guoda.preston.store.Archiver - failed to dereference [<https://zenodo.org/record/1480288/files/BM000561307.tif>]
java.net.SocketTimeoutException: Read timed out
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	at java.net.SocketInputStream.read(SocketInputStream.java:171)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at sun.security.ssl.InputRecord.readFully(InputRecord.java:465)
	at sun.security.ssl.InputRecord.readV3Record(InputRecord.java:593)
	at sun.security.ssl.InputRecord.read(InputRecord.java:532)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:983)
	at sun.security.ssl.SSLSocketImpl.readDataRecord(SSLSocketImpl.java:940)
	at sun.security.ssl.AppInputStream.read(AppInputStream.java:105)
	at org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:137)
	at org.apache.http.impl.io.SessionInputBufferImpl.read(SessionInputBufferImpl.java:197)
	at org.apache.http.impl.io.ContentLengthInputStream.read(ContentLengthInputStream.java:176)
	at org.apache.http.conn.EofSensorInputStream.read(EofSensorInputStream.java:135)
	at org.apache.commons.io.input.ProxyInputStream.read(ProxyInputStream.java:101)
	at java.security.DigestInputStream.read(DigestInputStream.java:161)
	at java.io.FilterInputStream.read(FilterInputStream.java:107)
	at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:1127)
	at org.apache.commons.io.IOUtils.copy(IOUtils.java:849)
	at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:1104)
	at org.apache.commons.io.IOUtils.copy(IOUtils.java:825)
	at bio.guoda.preston.Hasher.streamIntoMessageDigests(Hasher.java:85)
	at bio.guoda.preston.Hasher.calcHashIRIs(Hasher.java:121)
	at bio.guoda.preston.Hasher.calcHashIRI(Hasher.java:38)
	at bio.guoda.preston.store.BlobStoreAppendOnly.lambda$put$0(BlobStoreAppendOnly.java:27)
	at bio.guoda.preston.store.KeyValueStoreLocalFileSystem.put(KeyValueStoreLocalFileSystem.java:67)
	at bio.guoda.preston.store.KeyValueStoreWithFallback.put(KeyValueStoreWithFallback.java:19)
	at bio.guoda.preston.store.BlobStoreAppendOnly.put(BlobStoreAppendOnly.java:26)
	at bio.guoda.preston.store.DereferencerContentAddressed.get(DereferencerContentAddressed.java:22)
	at bio.guoda.preston.store.DereferencerContentAddressed.get(DereferencerContentAddressed.java:8)
	at bio.guoda.preston.store.Archiver.handleBlankVersion(Archiver.java:49)
	at bio.guoda.preston.store.VersionProcessor.on(VersionProcessor.java:28)
	at bio.guoda.preston.process.StatementsListenerEmitterAdapter.on(StatementsListenerEmitterAdapter.java:12)
	at bio.guoda.preston.cmd.CmdUpdate.processQueue(CmdUpdate.java:61)
	at bio.guoda.preston.cmd.CmdActivity.run(CmdActivity.java:114)
	at bio.guoda.preston.cmd.CmdActivity.run(CmdActivity.java:82)
	at bio.guoda.preston.cmd.CmdLine.run(CmdLine.java:18)
	at bio.guoda.preston.cmd.CmdLine.run(CmdLine.java:26)
	at bio.guoda.preston.Preston.main(Preston.java:14)
<https://deeplinker.bio/.well-known/genid/396cd258-e939-30d1-9104-d361760debc9> <http://www.w3.org/ns/prov#wasGeneratedBy> <urn:uuid:957cb7d1-9c9f-46f7-b0df-6076b4f55018> <urn:uuid:957cb7d1-9c9f-46f7-b0df-6076b4f55018> .
<https://deeplinker.bio/.well-known/genid/396cd258-e939-30d1-9104-d361760debc9> <http://www.w3.org/ns/prov#qualifiedGeneration> <urn:uuid:957cb7d1-9c9f-46f7-b0df-6076b4f55018> <urn:uuid:957cb7d1-9c9f-46f7-b0df-6076b4f55018> .
<urn:uuid:957cb7d1-9c9f-46f7-b0df-6076b4f55018> <http://www.w3.org/ns/prov#generatedAtTime> "2022-03-25T13:38:24.036Z"^^<http://www.w3.org/2001/XMLSchema#dateTime> <urn:uuid:957cb7d1-9c9f-46f7-b0df-6076b4f55018> .
<urn:uuid:957cb7d1-9c9f-46f7-b0df-6076b4f55018> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://www.w3.org/ns/prov#Generation> <urn:uuid:957cb7d1-9c9f-46f7-b0df-6076b4f55018> .
<urn:uuid:957cb7d1-9c9f-46f7-b0df-6076b4f55018> <http://www.w3.org/ns/prov#wasInformedBy> <urn:uuid:4cdce8bc-4ca5-415a-b48e-36085c0240bc> <urn:uuid:957cb7d1-9c9f-46f7-b0df-6076b4f55018> .
<urn:uuid:957cb7d1-9c9f-46f7-b0df-6076b4f55018> <http://www.w3.org/ns/prov#used> <https://zenodo.org/record/1480288/files/BM000561307.tif> <urn:uuid:957cb7d1-9c9f-46f7-b0df-6076b4f55018> .
<https://zenodo.org/record/1480288/files/BM000561307.tif> <http://purl.org/pav/hasVersion> <https://deeplinker.bio/.well-known/genid/396cd258-e939-30d1-9104-d361760debc9> <urn:uuid:957cb7d1-9c9f-46f7-b0df-6076b4f55018> .
```

**Comment by jhpoelen** [comment]
I got lucky this time :1st_place_medal: 

```
$ preston track --algo md5 https://zenodo.org/record/1480288/files/BM000561307.tif
<https://preston.guoda.bio> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://www.w3.org/ns/prov#SoftwareAgent> <urn:uuid:6420783d-b3f3-4167-99d7-41ef36598e0e> .
<https://preston.guoda.bio> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://www.w3.org/ns/prov#Agent> <urn:uuid:6420783d-b3f3-4167-99d7-41ef36598e0e> .
<https://preston.guoda.bio> <http://purl.org/dc/terms/description> "Preston is a software program that finds, archives and provides access to biodiversity datasets."@en <urn:uuid:6420783d-b3f3-4167-99d7-41ef36598e0e> .
<urn:uuid:6420783d-b3f3-4167-99d7-41ef36598e0e> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://www.w3.org/ns/prov#Activity> <urn:uuid:6420783d-b3f3-4167-99d7-41ef36598e0e> .
<urn:uuid:6420783d-b3f3-4167-99d7-41ef36598e0e> <http://purl.org/dc/terms/description> "A crawl event that discovers biodiversity archives."@en <urn:uuid:6420783d-b3f3-4167-99d7-41ef36598e0e> .
<urn:uuid:6420783d-b3f3-4167-99d7-41ef36598e0e> <http://www.w3.org/ns/prov#startedAtTime> "2022-03-25T13:46:15.043Z"^^<http://www.w3.org/2001/XMLSchema#dateTime> <urn:uuid:6420783d-b3f3-4167-99d7-41ef36598e0e> .
<urn:uuid:6420783d-b3f3-4167-99d7-41ef36598e0e> <http://www.w3.org/ns/prov#wasStartedBy> <https://preston.guoda.bio> <urn:uuid:6420783d-b3f3-4167-99d7-41ef36598e0e> .
<https://doi.org/10.5281/zenodo.1410543> <http://www.w3.org/ns/prov#usedBy> <urn:uuid:6420783d-b3f3-4167-99d7-41ef36598e0e> <urn:uuid:6420783d-b3f3-4167-99d7-41ef36598e0e> .
<https://doi.org/10.5281/zenodo.1410543> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://purl.org/dc/dcmitype/Software> <urn:uuid:6420783d-b3f3-4167-99d7-41ef36598e0e> .
<https://doi.org/10.5281/zenodo.1410543> <http://purl.org/dc/terms/bibliographicCitation> "Jorrit Poelen, Icaro Alzuru, & Michael Elliott. 2021. Preston: a biodiversity dataset tracker (Version 0.0.1-SNAPSHOT) [Software]. Zenodo. http://doi.org/10.5281/zenodo.1410543"@en <urn:uuid:6420783d-b3f3-4167-99d7-41ef36598e0e> .
<urn:uuid:0659a54f-b713-4f86-a917-5be166a14110> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://www.w3.org/ns/prov#Entity> <urn:uuid:6420783d-b3f3-4167-99d7-41ef36598e0e> .
<urn:uuid:0659a54f-b713-4f86-a917-5be166a14110> <http://purl.org/dc/terms/description> "A biodiversity dataset graph archive."@en <urn:uuid:6420783d-b3f3-4167-99d7-41ef36598e0e> .
<hash://md5/721e8329e1cdffa06398bc5214a14d3e> <http://www.w3.org/ns/prov#usedBy> <urn:uuid:6420783d-b3f3-4167-99d7-41ef36598e0e> <urn:uuid:6420783d-b3f3-4167-99d7-41ef36598e0e> .
<hash://md5/54912d475b8653c8949100abb046bfd2> <http://www.w3.org/ns/prov#wasGeneratedBy> <urn:uuid:00fe0af7-5536-4a2b-9f06-89a9927ee655> <urn:uuid:00fe0af7-5536-4a2b-9f06-89a9927ee655> .
<hash://md5/54912d475b8653c8949100abb046bfd2> <http://www.w3.org/ns/prov#qualifiedGeneration> <urn:uuid:00fe0af7-5536-4a2b-9f06-89a9927ee655> <urn:uuid:00fe0af7-5536-4a2b-9f06-89a9927ee655> .
<urn:uuid:00fe0af7-5536-4a2b-9f06-89a9927ee655> <http://www.w3.org/ns/prov#generatedAtTime> "2022-03-25T13:49:01.494Z"^^<http://www.w3.org/2001/XMLSchema#dateTime> <urn:uuid:00fe0af7-5536-4a2b-9f06-89a9927ee655> .
<urn:uuid:00fe0af7-5536-4a2b-9f06-89a9927ee655> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://www.w3.org/ns/prov#Generation> <urn:uuid:00fe0af7-5536-4a2b-9f06-89a9927ee655> .
<urn:uuid:00fe0af7-5536-4a2b-9f06-89a9927ee655> <http://www.w3.org/ns/prov#wasInformedBy> <urn:uuid:6420783d-b3f3-4167-99d7-41ef36598e0e> <urn:uuid:00fe0af7-5536-4a2b-9f06-89a9927ee655> .
<urn:uuid:00fe0af7-5536-4a2b-9f06-89a9927ee655> <http://www.w3.org/ns/prov#used> <https://zenodo.org/record/1480288/files/BM000561307.tif> <urn:uuid:00fe0af7-5536-4a2b-9f06-89a9927ee655> .
<https://zenodo.org/record/1480288/files/BM000561307.tif> <http://purl.org/pav/hasVersion> <hash://md5/54912d475b8653c8949100abb046bfd2> <urn:uuid:00fe0af7-5536-4a2b-9f06-89a9927ee655> .
```

note that the independently calculated md5 hash matches the one reported by Zenodo pub.

**Comment by jhpoelen** [comment]
@slint any idea how pervasive this intermittent artifact retrieval challenge is?

**Comment by jhpoelen** [comment]
@slint would you like me to keep this issue open, or would you say its an issue that is known to occur every once in a while and is inherent to the design of the Zenodo server architecture?
